export enum ClientErrorCode {
  UNKNOWN = 'UNKNOWN',
  INITIALIZE_FAILED = 'INITIALIZE_FAILED',
  API_REQUEST_FAILED = 'API_REQUEST_FAILED',
  INVALID_PARAM = 'INVALID_PARAM',
  INVALID_FORM = 'INVALID_FORM',
  RESPONSE_PARSE_FAILED = 'RESPONSE_PARSE_FAILED',
}
