import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/styles/global.css';

import { cn } from '@/shared/utils/cn';

import ToastProvider from '@/providers/ToastProvider';
import QueryProvider from '@/providers/QueryProvider';

export const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen antialiased', pretendard.className)}>
        <ToastProvider />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
