export enum OrderErrorCode {
  WALLET_INSUFFICIENT_BALANCE = 'WALLET_INSUFFICIENT_BALANCE',
  INVALID_DEPOSIT_AMOUNT = 'INVALID_DEPOSIT_AMOUNT',
  INVALID_WITHDRAW_AMOUNT = 'INVALID_WITHDRAW_AMOUNT',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  INVALID_AMOUNT_SCALE = 'INVALID_AMOUNT_SCALE',
  EXCHANGE_RATE_MISMATCH = 'EXCHANGE_RATE_MISMATCH',
  EXCHANGE_RATE_CURRENCY_MISMATCH = 'EXCHANGE_RATE_CURRENCY_MISMATCH',
  UNSUPPORTED_FOREX_CONVERSION_CURRENCY = 'UNSUPPORTED_FOREX_CONVERSION_CURRENCY',
  INVALID_EXCHANGE_RATE_CURRENCY = 'INVALID_EXCHANGE_RATE_CURRENCY',
  UNSUPPORTED_CURRENCY_FOR_KRW_CONVERSION = 'UNSUPPORTED_CURRENCY_FOR_KRW_CONVERSION',

  AMOUNT_NOT_PROVIDED = 'AMOUNT_NOT_PROVIDED',
  CURRENCY_NOT_PROVIDED = 'CURRENCY_NOT_PROVIDED',
}
